import {
  VoicePersona,
  VoicePreset,
  ContentType,
  CommercialSubStyle,
  VoiceAge,
  VoiceGender,
  VoiceRegion,
} from '../types/index.ts';

export const VOICE_PERSONAS: VoicePersona[] = [
  {
    id: 'mai_phuong',
    name: 'Mai Phương',
    baseVoice: 'Kore',
    gender: 'female',
    age: 'middle_aged',
    region: 'north',
    avatarIcon: '👩‍💼',
    title: 'Mai Phương · BTV Thời Sự & Văn Kiện',
    tagline: 'Trang trọng, chính thống, chuẩn xác từng câu chữ, âm chuẩn đài truyền hình',
    bestFor: 'Văn bản chính trị, báo cáo lãnh đạo, tin tức, tài liệu hội nghị',
    accentLabel: 'Hà Nội (Chuẩn BTV)',
    sampleAudioText:
      'Kính thưa các đồng chí, hôm nay chúng ta tập trung đánh giá các nhiệm vụ trọng tâm và phương hướng phát triển kinh tế xã hội năm 2026.',
  },
  {
    id: 'quoc_dung',
    name: 'Quốc Dũng',
    baseVoice: 'Charon',
    gender: 'male',
    age: 'middle_aged',
    region: 'north',
    avatarIcon: '👨‍💼',
    title: 'Quốc Dũng · Chính Luận & Lãnh Đạo',
    tagline: 'Đĩnh đạc, uy quyền, dứt khoát, âm vực trầm vang, mang tính khẳng định và định hướng',
    bestFor: 'Văn bản nghị quyết, báo cáo chiến lược, tổng kết thành tựu',
    accentLabel: 'Hà Nội (Chính luận)',
    sampleAudioText:
      'Cần tiếp tục nâng cao năng lực quản trị, đẩy mạnh đổi mới sáng tạo, bảo đảm hoàn thành thắng lợi các mục tiêu chiến lược.',
  },
  {
    id: 'manh_dung',
    name: 'Mạnh Dũng',
    baseVoice: 'Fenrir',
    gender: 'male',
    age: 'middle_aged',
    region: 'north',
    avatarIcon: '🎙️',
    title: 'Mạnh Dũng · Phóng Sự & Phim Tài Liệu',
    tagline: 'Trầm ấm, sâu lắng, đậm chất tự sự, ngắt nghỉ có chiều sâu không gian',
    bestFor: 'Phim tài liệu, phóng sự ký sự, hồi ký lịch sử, sách nói văn học',
    accentLabel: 'Miền Bắc (Trầm ấm)',
    sampleAudioText:
      'Dưới chân dãy Trường Sơn hùng vĩ, những chứng tích lịch sử vẫn vẹn nguyên như mới ngày hôm qua, gợi nhắc về một thời hoa lửa.',
  },
  {
    id: 'lan_anh',
    name: 'Lan Anh',
    baseVoice: 'Zephyr',
    gender: 'female',
    age: 'young_adult',
    region: 'north',
    avatarIcon: '👩‍💻',
    title: 'Lan Anh · Thuyết Minh & Sách Nói',
    tagline: 'Trong sáng, rõ ràng, dứt khoát, tốc độ vừa phải, dễ tiếp thu',
    bestFor: 'Bản tin sự kiện, sách nói, video giới thiệu, bài giảng trực tuyến',
    accentLabel: 'Hà Nội (Hiện đại)',
    sampleAudioText:
      'Chào mừng quý vị và các bạn đến với bản tin kinh tế số hôm nay với nhiều xu hướng công nghệ nổi bật trong quý vừa qua.',
  },
  {
    id: 'thao_vy',
    name: 'Thảo Vy',
    baseVoice: 'Kore',
    gender: 'female',
    age: 'young_adult',
    region: 'south',
    avatarIcon: '🌸',
    title: 'Thảo Vy · TVC & Podcast Miền Nam',
    tagline: 'Ngọt ngào, tự nhiên, thân thiện, gần gũi, cuốn hút người nghe',
    bestFor: 'Quảng cáo sản phẩm, podcast đời sống, TikTok, video mạng xã hội',
    accentLabel: 'Sài Gòn (Thân thiện)',
    sampleAudioText:
      'Chào các bạn, hôm nay hãy cùng mình khám phá những sản phẩm tuyệt vời nhất để mang lại năng lượng tích cực cho cả ngày nhé!',
  },
  {
    id: 'minh_hoang',
    name: 'Minh Hoàng',
    baseVoice: 'Puck',
    gender: 'male',
    age: 'young_adult',
    region: 'north',
    avatarIcon: '⚡',
    title: 'Minh Hoàng · TikTok & TVC Sôi Nổi',
    tagline: 'Trẻ trung, năng lượng bùng nổ, nhịp điệu nhanh, thu hút ngay câu mở đầu',
    bestFor: 'Shorts, Reels, TikTok review, quảng cáo khuyến mãi sốt dẻo',
    accentLabel: 'Toàn quốc (Năng động)',
    sampleAudioText:
      'Bạn đã biết điều này chưa? Đừng bỏ lỡ ưu đãi cực sốc chỉ có trong hôm nay, đăng ký ngay để nhận quà liền tay!',
  },
  {
    id: 'bac_huu_nam',
    name: 'Bác Hữu Nam',
    baseVoice: 'Fenrir',
    gender: 'male',
    age: 'elderly',
    region: 'south',
    avatarIcon: '👴',
    title: 'Bác Hữu Nam · Truyện Đêm & Hồi Ký',
    tagline: 'Giọng trầm của người từng trải, mộc mạc, từ tốn, ấm lòng như người thân',
    bestFor: 'Sách nói đêm muộn, hồi ký văn hóa, truyện cổ tích',
    accentLabel: 'Nam Bộ (Truyền thống)',
    sampleAudioText:
      'Đêm nay bên dòng sông êm ả, tôi xin kể lại cho các cháu nghe về những ngày đầu mở cõi nơi đất phương Nam trù phú.',
  },
  {
    id: 'be_bong',
    name: 'Bé Bống',
    baseVoice: 'Zephyr',
    gender: 'female',
    age: 'child',
    region: 'north',
    avatarIcon: '👧',
    title: 'Bé Bống · Truyện Thiếu Nhi & Cổ Tích',
    tagline: 'Trong trẻo, hồn nhiên, líu lo đáng yêu, ngắt nghỉ ngây thơ chuẩn bé gái 7 tuổi',
    bestFor: 'Truyện thiếu nhi, hoạt hình, bài học mầm non, truyện tranh tương tác',
    accentLabel: 'Hà Nội (Bé gái 7 tuổi)',
    badge: 'Phổ biến nhất',
    voiceStylePrompt:
      'High-pitched, very sweet, pure, innocent and cheerful Vietnamese 7-year-old girl voice (bé gái 7 tuổi), lively, playful, enthusiastic and adorable bright melodic intonation.',
    sampleAudioText:
      'Xin chào các bạn nhỏ! Hôm nay chúng mình cùng lắng nghe câu chuyện Thỏ và Rùa chạy thi trong khu rừng xanh thật vui vẻ nhé!',
  },
  {
    id: 'be_bo',
    name: 'Bé Bo',
    baseVoice: 'Puck',
    gender: 'male',
    age: 'child',
    region: 'north',
    avatarIcon: '👦',
    title: 'Bé Bo · Hoạt Hình & Khám Phá Khoa Học',
    tagline: 'Tinh nghịch, tò mò, hào hứng, hoạt bát và tràn đầy năng lượng tuổi thơ 8 tuổi',
    bestFor: 'Video khám phá thế giới, khoa học vui cho bé, nhân vật hoạt hình nhí',
    accentLabel: 'Toàn quốc (Bé trai 8 tuổi)',
    badge: 'Tinh nghịch',
    voiceStylePrompt:
      'High-pitched energetic, curious and mischievous 8-year-old Vietnamese boy voice (bé trai 8 tuổi), enthusiastic, lively cartoon character tone.',
    sampleAudioText:
      'Oa, các bạn nhìn kìa! Chú khủng long khổng lồ đang bước đi, tuyệt vời quá đi thôi, chúng mình cùng đuổi theo xem nào!',
  },
  {
    id: 'be_mai_anh',
    name: 'Bé Mai Anh',
    baseVoice: 'Kore',
    gender: 'female',
    age: 'child',
    region: 'south',
    avatarIcon: '🎀',
    title: 'Bé Mai Anh · Thơ Ca & Truyện Cổ Tích Nam Bộ',
    tagline: 'Giọng Nam Bộ ngọt ngào, líu lo, ngây thơ, bẽn lẽn dễ thương 6 tuổi',
    bestFor: 'Thơ thiếu nhi, kể chuyện bé ngoan, bài hát mầm non, lời chúc mừng',
    accentLabel: 'Nam Bộ (Bé gái 6 tuổi)',
    badge: 'Dễ thương',
    voiceStylePrompt:
      'Sweet, gentle, charming Southern Vietnamese 6-year-old girl voice (bé gái Sài Gòn), adorable, cute and polite.',
    sampleAudioText:
      'Dạ, con xin chào ông bà và ba mẹ! Hôm nay ở trường con được cô khen và tặng phiếu bé ngoan nè, con vui lắm luôn á!',
  },
  {
    id: 'be_bin',
    name: 'Bé Bin',
    baseVoice: 'Puck',
    gender: 'male',
    age: 'child',
    region: 'south',
    avatarIcon: '🧒',
    title: 'Bé Bin · Hoạt Hình & Truyện Cười Nhí Nam Bộ',
    tagline: 'Lanh lợi, dõng dạc, hóm hỉnh, tếu táo chuẩn bé trai miền Nam 8 tuổi',
    bestFor: 'Truyện cười thiếu nhi, hoạt hình vui nhộn, đố vui có thưởng',
    accentLabel: 'Sài Gòn (Bé trai 8 tuổi)',
    badge: 'Lanh lợi',
    voiceStylePrompt:
      'Spirited, smart, witty Southern Vietnamese 8-year-old boy voice, bright, humorous and playful cartoon delivery.',
    sampleAudioText:
      'Chào các bạn, mình là Bin đây! Hôm nay mình sẽ đố các bạn một câu đố cực kỳ vui nhộn, xem bạn nào đoán đúng trước nha!',
  },
  {
    id: 'be_tho_con',
    name: 'Bé Thỏ Con',
    baseVoice: 'Zephyr',
    gender: 'female',
    age: 'child',
    region: 'north',
    avatarIcon: '🍼',
    title: 'Bé Thỏ Con · Mầm Non & Bé Tập Nói',
    tagline: 'Ngọng nghịu ngây thơ, đáng yêu tan chảy, chuẩn giọng em bé 4-5 tuổi học mẫu giáo',
    bestFor: 'Đồng dao cho bé, thơ chữ to tập nói, nhận biết con vật & màu sắc mầm non',
    accentLabel: 'Mầm non (Bé 4 tuổi)',
    badge: 'Đáng yêu',
    voiceStylePrompt:
      'High-pitched adorable 4-year-old preschool toddler voice (em bé mầm non), extremely cute, sweet childish lisp, cheerful and innocent.',
    sampleAudioText:
      'Con chào cô giáo ạ! Hôm nay con biết đọc thơ chú thỏ trắng tai dài mắt hồng rồi nè, cô vỗ tay khen con nha!',
  },
  {
    id: 'minh_anh',
    name: 'Minh Anh',
    baseVoice: 'Kore',
    gender: 'female',
    age: 'child',
    region: 'north',
    avatarIcon: '🎒',
    title: 'Minh Anh · Tập Đọc SGK & Đạo Đức',
    tagline: 'Dõng dạc, chuẩn chính tả Tiếng Việt, ngắt nhịp câu chuẩn mực học sinh tiểu học',
    bestFor: 'Bài tập đọc Tiếng Việt SGK, đọc truyện đạo đức, phát thanh sao nhi đồng',
    accentLabel: 'Hà Nội (Học sinh lớp 4)',
    badge: 'Học sinh ngoan',
    voiceStylePrompt:
      'Clear, polite, articulate 10-year-old Vietnamese student voice, neat, educational, well-paced textbook reading tone.',
    sampleAudioText:
      'Kính chào thầy cô và các bạn, sau đây em xin phép được đọc bài tập đọc: Đôi bạn tốt trên đường tới trường.',
  },
  {
    id: 'tuan_khang',
    name: 'Tuấn Khang',
    baseVoice: 'Charon',
    gender: 'male',
    age: 'child',
    region: 'central',
    avatarIcon: '🎺',
    title: 'Tuấn Khang · Đội Viên Măng Non',
    tagline: 'Khỏe khoắn, tự hào, dõng dạc, rõ ràng, tinh thần đội viên măng non',
    bestFor: 'Phát thanh học đường, nghi thức đội, hoạt động Đoàn Đội thiếu nhi',
    accentLabel: 'Dõng dạc (Bé trai 9 tuổi)',
    badge: 'Đội viên',
    voiceStylePrompt:
      'Confident, spirited 9-year-old schoolboy voice, clear diction, proud and articulate pioneer radio presenter tone.',
    sampleAudioText:
      'Mời các bạn lắng nghe chương trình phát thanh Măng Non tuần này với các tấm gương bạn tốt việc tốt trong trường chúng ta!',
  },
  {
    id: 'chi_tho_ngoc',
    name: 'Chị Thỏ Ngọc',
    baseVoice: 'Kore',
    gender: 'female',
    age: 'young_adult',
    region: 'north',
    avatarIcon: '🌙',
    title: 'Chị Thỏ Ngọc · Kể Chuyện Ru Ngủ Bé Yêu',
    tagline: 'Thủ thỉ, dịu êm, ấm áp như cô tiên, vỗ về bé vào giấc ngủ thần tiên ngọt ngào',
    bestFor: 'Truyện cổ tích đêm muộn, podcast ru bé ngủ, lời thì thầm giấc mơ đẹp',
    accentLabel: 'Dịu dàng (Ru bé ngủ)',
    badge: 'Ru ngủ',
    voiceStylePrompt:
      'Very gentle, whispering, soothing bedtime storyteller voice for little children, peaceful, warm, comforting and dreamy tone.',
    sampleAudioText:
      'Bé yêu ơi, trăng sao đã lên cao rồi. Nào, bé hãy nhắm mắt lại, đắp chăn ấm và cùng lắng nghe câu chuyện cổ tích êm đềm nhé.',
  },
];

export const CONTENT_TYPES_CONFIG: {
  id: ContentType;
  label: string;
  icon: string;
  subtitle: string;
  pacingNote: string;
  emphasisRules: string[];
}[] = [
  {
    id: 'political',
    label: 'Văn bản chính trị, báo cáo lãnh đạo',
    icon: '🏛️',
    subtitle: 'Trang trọng · Chính thống · Khẳng định · Định hướng · Bình tĩnh & Chắc chắn',
    pacingNote: 'Tốc độ vừa phải, phát âm rõ ràng, ngắt nghỉ cẩn trọng ở câu nhiều mệnh đề',
    emphasisRules: [
      'Nhấn mục tiêu, nhiệm vụ và định hướng chiến lược',
      'Nhấn các số liệu tổng kết thành tựu',
      'Nhấn cụm từ: "nâng cao", "đáp ứng yêu cầu", "bảo đảm", "tăng cường", "phát huy", "đẩy mạnh", "tiếp tục", "mục tiêu"',
      'Hạ nhẹ cao độ, giọng nghiêm túc, khách quan khi nói về hạn chế và nguyên nhân',
    ],
  },
  {
    id: 'news',
    label: 'Bản tin thời sự, tin tức sự kiện',
    icon: '📰',
    subtitle: 'Khách quan · Nghiêm túc · Tin cậy · Rõ ràng · Tròn vành rõ chữ',
    pacingNote: 'Nhịp nhanh vừa, dứt khoát, đều đặn, không kịch tính giật gân',
    emphasisRules: [
      'Nhấn nhẹ vào thông tin quan trọng',
      'Đọc rõ ràng tên riêng, địa danh, thời gian và số liệu thống kê',
      'Hạn chế cảm xúc cá nhân, giữ tính trung lập',
    ],
  },
  {
    id: 'documentary',
    label: 'Phóng sự, phim tài liệu',
    icon: '🎬',
    subtitle: 'Trầm ấm · Sâu lắng · Tự sự · Có chiều sâu chiêm nghiệm',
    pacingNote: 'Nhịp chậm hơn bình thường, tạo khoảng lặng có chủ đích giữa các ý',
    emphasisRules: [
      'Phân biệt rõ: mô tả bối cảnh, dữ liệu, phân tích, nhận định và câu chuyện nhân vật',
      'Chuyển đổi sắc thái nhịp nhàng giữa các đoạn',
      'Không đọc đều đều một tông giọng từ đầu đến cuối',
    ],
  },
  {
    id: 'commercial',
    label: 'Video quảng cáo / TVC / Giới thiệu sản phẩm',
    icon: '📺',
    subtitle: 'Năng động · Tươi sáng · Sang trọng · Thu hút · Kêu gọi hành động',
    pacingNote: 'Năng lượng giọng cao, tiết tấu linh hoạt, cuốn hút từ giây đầu',
    emphasisRules: [
      'Nhấn mạnh tên thương hiệu và tên sản phẩm',
      'Nhấn mạnh USP và tính năng nổi bật',
      'Nhấn mạnh giá trị và ưu đãi',
      'Nhấn mạnh Call To Action ở cuối: "Đăng ký ngay", "Khám phá ngay", "Mua ngay"',
    ],
  },
  {
    id: 'audiobook',
    label: 'Sách nói / Audiobook / Kể chuyện',
    icon: '📚',
    subtitle: 'Truyền cảm · Tự nhiên · Gần gũi · Linh hoạt theo diễn biến truyện',
    pacingNote: 'Thay đổi nhịp đọc theo nhịp cảm xúc, tạo khoảng nghỉ cho thính giả tưởng tượng',
    emphasisRules: [
      'Điều chỉnh cao độ và cường độ theo kịch tính câu chuyện',
      'Phân biệt rõ lời người kể chuyện và lời thoại nhân vật',
      'Tạo khoảng nghỉ phù hợp giữa các đoạn văn chuyển cảnh',
    ],
  },
  {
    id: 'tiktok',
    label: 'TikTok / Reels / Shorts / Video ngắn',
    icon: '📱',
    subtitle: 'Tự nhiên · Conversational · Năng lượng cao · Bắt tai ngay câu mở đầu',
    pacingNote: 'Tốc độ nhanh, nhịp câu sôi nổi, không cứng nhắc theo lối hành chính',
    emphasisRules: [
      'Tạo điểm nhấn mạnh mẽ và kích thích tò mò ngay từ câu đầu (hook)',
      'Nhịp điệu dồn dập, ngữ điệu lên xuống tự nhiên như đang trò chuyện trực tiếp',
      'Giữ sự chú ý xuyên suốt video',
    ],
  },
  {
    id: 'kids',
    label: 'Truyện thiếu nhi, cổ tích & Hoạt hình',
    icon: '🧸',
    subtitle: 'Hồn nhiên · Trong trẻo · Líu lo · Đáng yêu · Vui nhộn cho bé',
    pacingNote: 'Ngữ điệu vui tươi, nhịp điệu sinh động, giàu hình tượng, ngắt nghỉ ngây thơ chuẩn lứa tuổi thiếu nhi',
    emphasisRules: [
      'Nhấn mạnh vào tên nhân vật đáng yêu (Thỏ trắng, Rùa con, Bé ngoan, Chú Gấu bông, Cô Tiên)',
      'Nhấn vào các từ tượng thanh, tượng hình: "líu lo", "thoăn thoắt", "vút bay", "khổng lồ", "lung linh"',
      'Biểu cảm ngạc nhiên, hào hứng tột cùng khi diễn biến câu chuyện mở ra',
      'Đọc chậm rãi, ấm áp và trìu mến ở đoạn kết bài học bé ngoan',
    ],
  },
];

export const VOICE_PRESETS: VoicePreset[] = [
  {
    id: 'preset_political',
    name: 'Chính luận lãnh đạo',
    icon: '🏛️',
    description: 'Nam · Trung niên · Miền Bắc · Trang trọng · Nghiêm túc · Tốc độ vừa',
    contentType: 'political',
    gender: 'male',
    age: 'middle_aged',
    region: 'north',
    personaId: 'quoc_dung',
    speed: 1.0,
    pitch: 0,
    energy: 'medium',
    pause: 'medium',
    emphasis: 'high',
    emotion: 'serious',
  },
  {
    id: 'preset_news',
    name: 'Phát thanh thời sự',
    icon: '📰',
    description: 'Nữ/Nam · Trung niên · Miền Bắc · Rõ chữ · Dứt khoát · Chuẩn mực',
    contentType: 'news',
    gender: 'female',
    age: 'middle_aged',
    region: 'north',
    personaId: 'mai_phuong',
    speed: 1.05,
    pitch: 0,
    energy: 'medium',
    pause: 'medium',
    emphasis: 'medium',
    emotion: 'neutral',
  },
  {
    id: 'preset_documentary',
    name: 'Phim tài liệu',
    icon: '🎬',
    description: 'Nam · Trung niên · Trầm ấm · Chậm · Sâu lắng · Khoảng lặng giàu cảm xúc',
    contentType: 'documentary',
    gender: 'male',
    age: 'middle_aged',
    region: 'north',
    personaId: 'manh_dung',
    speed: 0.9,
    pitch: -2,
    energy: 'medium',
    pause: 'long',
    emphasis: 'high',
    emotion: 'warm',
  },
  {
    id: 'preset_ad_energy',
    name: 'Quảng cáo năng lượng',
    icon: '📢',
    description: 'Nam · Thanh niên · Năng lượng cao · Nhanh · Tươi sáng · Nhấn CTA',
    contentType: 'commercial',
    gender: 'male',
    age: 'young_adult',
    region: 'north',
    personaId: 'minh_hoang',
    speed: 1.2,
    pitch: 2,
    energy: 'high',
    pause: 'short',
    emphasis: 'high',
    emotion: 'expressive',
  },
  {
    id: 'preset_ad_luxury',
    name: 'Quảng cáo cao cấp',
    icon: '💎',
    description: 'Nữ · Trung niên · Trầm ấm · Sang trọng · Đẳng cấp · Chậm vừa',
    contentType: 'commercial',
    gender: 'female',
    age: 'middle_aged',
    region: 'north',
    personaId: 'mai_phuong',
    speed: 0.95,
    pitch: -1,
    energy: 'medium',
    pause: 'medium',
    emphasis: 'high',
    emotion: 'expressive',
  },
  {
    id: 'preset_audiobook',
    name: 'Sách nói văn học',
    icon: '📚',
    description: 'Nữ · Tự nhiên · Truyền cảm · Linh hoạt theo mạch truyện',
    contentType: 'audiobook',
    gender: 'female',
    age: 'young_adult',
    region: 'north',
    personaId: 'lan_anh',
    speed: 0.95,
    pitch: 0,
    energy: 'medium',
    pause: 'medium',
    emphasis: 'medium',
    emotion: 'warm',
  },
  {
    id: 'preset_storytelling',
    name: 'Kể chuyện tự sự',
    icon: '🎭',
    description: 'Nam · Người già/Trung niên · Miền Nam · Mộc mạc · Giàu hoài niệm',
    contentType: 'audiobook',
    gender: 'male',
    age: 'elderly',
    region: 'south',
    personaId: 'bac_huu_nam',
    speed: 0.9,
    pitch: -3,
    energy: 'medium',
    pause: 'long',
    emphasis: 'medium',
    emotion: 'warm',
  },
  {
    id: 'preset_tiktok',
    name: 'TikTok / Shorts',
    icon: '📱',
    description: 'Nam/Nữ · Thanh niên · Năng lượng cao · Nhanh · Conversational bắt trend',
    contentType: 'tiktok',
    gender: 'male',
    age: 'young_adult',
    region: 'north',
    personaId: 'minh_hoang',
    speed: 1.25,
    pitch: 1,
    energy: 'high',
    pause: 'short',
    emphasis: 'high',
    emotion: 'expressive',
  },
  {
    id: 'preset_education',
    name: 'Bài giảng giáo dục',
    icon: '🎓',
    description: 'Nữ · Trung niên · Rõ ràng · Điềm tĩnh · Mô phạm · Dễ tiếp thu',
    contentType: 'news',
    gender: 'female',
    age: 'young_adult',
    region: 'north',
    personaId: 'lan_anh',
    speed: 1.0,
    pitch: 0,
    energy: 'medium',
    pause: 'medium',
    emphasis: 'medium',
    emotion: 'neutral',
  },
  {
    id: 'preset_kids_fairy',
    name: 'Cổ tích Bé Bống',
    icon: '🎈',
    description: 'Bé gái 7 tuổi · Hà Nội · Hồn nhiên · Líu lo trong trẻo · Truyện cổ tích',
    contentType: 'kids',
    gender: 'female',
    age: 'child',
    region: 'north',
    personaId: 'be_bong',
    speed: 1.0,
    pitch: 4,
    energy: 'high',
    pause: 'medium',
    emphasis: 'high',
    emotion: 'expressive',
  },
  {
    id: 'preset_kids_cartoon',
    name: 'Hoạt hình Bé Bo',
    icon: '🚀',
    description: 'Bé trai 8 tuổi · Tinh nghịch · Tò mò · Hào hứng · Phim hoạt hình',
    contentType: 'kids',
    gender: 'male',
    age: 'child',
    region: 'north',
    personaId: 'be_bo',
    speed: 1.1,
    pitch: 4,
    energy: 'high',
    pause: 'short',
    emphasis: 'high',
    emotion: 'expressive',
  },
  {
    id: 'preset_kids_south',
    name: 'Bé Mai Anh Nam Bộ',
    icon: '🎀',
    description: 'Bé gái 6 tuổi · Nam Bộ · Ngọt ngào · Ngoan ngoãn · Đọc thơ thiếu nhi',
    contentType: 'kids',
    gender: 'female',
    age: 'child',
    region: 'south',
    personaId: 'be_mai_anh',
    speed: 1.0,
    pitch: 4,
    energy: 'high',
    pause: 'medium',
    emphasis: 'high',
    emotion: 'expressive',
  },
  {
    id: 'preset_kids_bin',
    name: 'Bé Bin lanh lợi',
    icon: '🧒',
    description: 'Bé trai 8 tuổi · Miền Nam · Lanh lợi · Truyện cười vui nhộn',
    contentType: 'kids',
    gender: 'male',
    age: 'child',
    region: 'south',
    personaId: 'be_bin',
    speed: 1.08,
    pitch: 3,
    energy: 'high',
    pause: 'short',
    emphasis: 'high',
    emotion: 'expressive',
  },
  {
    id: 'preset_kids_preschool',
    name: 'Mầm Non Thỏ Con',
    icon: '🍼',
    description: 'Em bé 4 tuổi · Ngọng nghịu đáng yêu · Bé tập nói & đồng dao',
    contentType: 'kids',
    gender: 'female',
    age: 'child',
    region: 'north',
    personaId: 'be_tho_con',
    speed: 0.95,
    pitch: 5,
    energy: 'high',
    pause: 'long',
    emphasis: 'high',
    emotion: 'expressive',
  },
  {
    id: 'preset_kids_school',
    name: 'Tập đọc Tiểu học',
    icon: '🎒',
    description: 'Học sinh lớp 4 · Chuẩn mực Tiếng Việt · Dõng dạc bài tập đọc SGK',
    contentType: 'kids',
    gender: 'female',
    age: 'child',
    region: 'north',
    personaId: 'minh_anh',
    speed: 0.95,
    pitch: 2,
    energy: 'medium',
    pause: 'medium',
    emphasis: 'high',
    emotion: 'neutral',
  },
  {
    id: 'preset_kids_lullaby',
    name: 'Ru bé ngủ ngon',
    icon: '🌙',
    description: 'Chị Thỏ Ngọc · Dịu dàng êm ái · Kể chuyện đêm khuya cho bé ngủ say',
    contentType: 'kids',
    gender: 'female',
    age: 'young_adult',
    region: 'north',
    personaId: 'chi_tho_ngoc',
    speed: 0.85,
    pitch: 1,
    energy: 'low',
    pause: 'long',
    emphasis: 'low',
    emotion: 'warm',
  },
];
